config/routes.rb
Rails.application.routes.draw do
  resources :work_products
  resources :categories
  resources :reference_models
  resources :process_areas
  get 'static_pages/home'

  resources :capacity_levels
  resources :maturity_levels
  resources :specific_goals
  resources :specific_practices
  resources :generic_goals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/capacity_level.rb
class CapacityLevel < ApplicationRecord
  has_many :generic_goals
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :process_areas
end

app/models/generic_goal.rb
class GenericGoal < ApplicationRecord
  has_many :capacity_levels
end

app/models/maturity_level.rb
class MaturityLevel < ApplicationRecord
  has_many :process_areas
end

app/models/process_area.rb
class ProcessArea < ApplicationRecord
  belongs_to :reference_model
  belongs_to :category
  belongs_to :maturity_level
end

app/models/reference_model.rb
class ReferenceModel < ApplicationRecord
  belongs_to :area_process
  belongs_to :generic_goal
end

app/models/specific_goal.rb
class SpecificGoal < ApplicationRecord
  belongs_to :specific_practice

  has_many :process_areas
end

app/models/specific_practice.rb
class SpecificPractice < ApplicationRecord
  has_many :specific_goals
end

app/models/work_product.rb
class WorkProduct < ApplicationRecord
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/work_products_controller.rb
class WorkProductsController < ApplicationController
  before_action :set_work_product, only: [:show, :edit, :update, :destroy]

  # GET /work_products
  # GET /work_products.json
  def index
    @work_products = WorkProduct.all
  end

  # GET /work_products/1
  # GET /work_products/1.json
  def show
  end

  # GET /work_products/new
  def new
    @work_product = WorkProduct.new
  end

  # GET /work_products/1/edit
  def edit
  end

  # POST /work_products
  # POST /work_products.json
  def create
    @work_product = WorkProduct.new(work_product_params)

    respond_to do |format|
      if @work_product.save
        format.html { redirect_to @work_product, notice: 'Work product was successfully created.' }
        format.json { render :show, status: :created, location: @work_product }
      else
        format.html { render :new }
        format.json { render json: @work_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_products/1
  # PATCH/PUT /work_products/1.json
  def update
    respond_to do |format|
      if @work_product.update(work_product_params)
        format.html { redirect_to @work_product, notice: 'Work product was successfully updated.' }
        format.json { render :show, status: :ok, location: @work_product }
      else
        format.html { render :edit }
        format.json { render json: @work_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_products/1
  # DELETE /work_products/1.json
  def destroy
    @work_product.destroy
    respond_to do |format|
      format.html { redirect_to work_products_url, notice: 'Work product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_product
      @work_product = WorkProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_product_params
      params.require(:work_product).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/capacity_levels_helper.rb
module CapacityLevelsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/generic_goals_helper.rb
module GenericGoalsHelper
end

app/helpers/maturity_levels_helper.rb
module MaturityLevelsHelper
end

app/helpers/process_areas_helper.rb
module ProcessAreasHelper
end

app/helpers/reference_models_helper.rb
module ReferenceModelsHelper
end

app/helpers/specific_goals_helper.rb
module SpecificGoalsHelper
end

app/helpers/specific_practices_helper.rb
module SpecificPracticesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/work_products_helper.rb
module WorkProductsHelper
end

app/views/work_products/_form.html.erb
<%= form_for(work_product) do |f| %>
  <% if work_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work_product.errors.count, "error") %> prohibited this work_product from being saved:</h2>

      <ul>
      <% work_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br/>

  <div class="field">
    <%= f.label :name, "Nome" %>
    <%= f.text_field :name %>
  </div>

  <br/>

  <div class="actions">
    <%= f.submit("Enviar", :class => "btn btn-primary") %>
  </div>

  <br/>
<% end %>

app/views/work_products/edit.html.erb
<h1>Produtos de trabalho</h1>

<%= render 'form', work_product: @work_product %>

<%= link_to 'Visualizar', @work_product %> |
<%= link_to 'Voltar', work_products_path %>

app/views/work_products/index.html.erb
<h1>Produtos de trabalho</h1>

</br>

<a href="<%= new_work_product_path %>" class="btn btn-primary">
  <span class="glyphicon glyphicon-plus"></span>
  Cadastrar
</a>

<br/><br/>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @work_products.each do |work_product| %>
      <tr>
        <td><%= work_product.name %></td>
        <td><%= link_to 'Visualizar', work_product %></td>
        <td><%= link_to 'Editar', edit_work_product_path(work_product) %></td>
        <td><%= link_to 'Destroy', work_product, method: :delete, data: { confirm: 'Voce tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/work_products/new.html.erb
<h1>Novo Produto de trabalho</h1>

<%= render 'form', work_product: @work_product %>

<%= link_to 'Voltar', work_products_path %>

app/views/work_products/show.html.erb
 <p>
  <strong>Nome:</strong>
  <%= @work_product.name %>
</p>

<%= link_to 'Editar', edit_work_product_path(@work_product) %> |
<%= link_to 'Voltar', work_products_path %>