config/routes.rb
Rails.application.routes.draw do
  resources :work_products
  resources :categories
  resources :reference_models
  resources :process_areas
  get 'static_pages/home'

  resources :capacity_levels
  resources :maturity_levels
  resources :specific_goals
  resources :specific_practices
  resources :generic_goals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/capacity_level.rb
class CapacityLevel < ApplicationRecord
  has_many :generic_goals
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :process_areas
end

app/models/generic_goal.rb
class GenericGoal < ApplicationRecord
  has_many :capacity_levels
end

app/models/maturity_level.rb
class MaturityLevel < ApplicationRecord
  has_many :process_areas
end

app/models/process_area.rb
class ProcessArea < ApplicationRecord
  belongs_to :reference_model
  belongs_to :category
  belongs_to :maturity_level
end

app/models/reference_model.rb
class ReferenceModel < ApplicationRecord
  belongs_to :area_process
  belongs_to :generic_goal
end

app/models/specific_goal.rb
class SpecificGoal < ApplicationRecord
  belongs_to :specific_practice

  has_many :process_areas
end

app/models/specific_practice.rb
class SpecificPractice < ApplicationRecord
  has_many :specific_goals
end

app/models/work_product.rb
class WorkProduct < ApplicationRecord
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/specific_practices_controller.rb
class SpecificPracticesController < ApplicationController
  before_action :set_specific_practice, only: [:show, :edit, :update, :destroy]

  # GET /specific_practices
  # GET /specific_practices.json
  def index
    @specific_practices = SpecificPractice.all
  end

  # GET /specific_practices/1
  # GET /specific_practices/1.json
  def show
  end

  # GET /specific_practices/new
  def new
    @specific_practice = SpecificPractice.new
  end

  # GET /specific_practices/1/edit
  def edit
  end

  # POST /specific_practices
  # POST /specific_practices.json
  def create
    @specific_practice = SpecificPractice.new(specific_practice_params)

    respond_to do |format|
      if @specific_practice.save
        format.html { redirect_to @specific_practice, notice: 'Specific practice was successfully created.' }
        format.json { render :show, status: :created, location: @specific_practice }
      else
        format.html { render :new }
        format.json { render json: @specific_practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specific_practices/1
  # PATCH/PUT /specific_practices/1.json
  def update
    respond_to do |format|
      if @specific_practice.update(specific_practice_params)
        format.html { redirect_to @specific_practice, notice: 'Specific practice was successfully updated.' }
        format.json { render :show, status: :ok, location: @specific_practice }
      else
        format.html { render :edit }
        format.json { render json: @specific_practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specific_practices/1
  # DELETE /specific_practices/1.json
  def destroy
    @specific_practice.destroy
    respond_to do |format|
      format.html { redirect_to specific_practices_url, notice: 'Specific practice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_specific_practice
      @specific_practice = SpecificPractice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def specific_practice_params
      params.require(:specific_practice).permit(:name, :abbrev, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/capacity_levels_helper.rb
module CapacityLevelsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/generic_goals_helper.rb
module GenericGoalsHelper
end

app/helpers/maturity_levels_helper.rb
module MaturityLevelsHelper
end

app/helpers/process_areas_helper.rb
module ProcessAreasHelper
end

app/helpers/reference_models_helper.rb
module ReferenceModelsHelper
end

app/helpers/specific_goals_helper.rb
module SpecificGoalsHelper
end

app/helpers/specific_practices_helper.rb
module SpecificPracticesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/work_products_helper.rb
module WorkProductsHelper
end

app/views/specific_practices/_form.html.erb
<%= form_for(specific_practice) do |f| %>
  <% if specific_practice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(specific_practice.errors.count, "error") %> prohibited this specific_practice from being saved:</h2>

      <ul>
      <% specific_practice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br/>

  <div class="field">
    <%= f.label :name, "Nome" %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :abbrev, "Sigla" %>
    <%= f.text_field :abbrev %>
  </div>

  <div class="field">
    <%= f.label :description, "Descrição" %>
    <%= f.text_area :description %>
  </div>

  <br/>

  <div class="actions">
    <%= f.submit("Enviar", :class => "btn btn-primary") %>
  </div>

  <br/>
<% end %>

app/views/specific_practices/edit.html.erb
<h1>Prática Específica</h1>

<%= render 'form', specific_practice: @specific_practice %>

<%= link_to 'Visualizar', @specific_practice %> |
<%= link_to 'Voltar', specific_practices_path %>

app/views/specific_practices/index.html.erb
<h1>Práticas Específicas</h1>

<br/>

<a href="<%= new_specific_practice_path %>" class="btn btn-primary">
  <span class="glyphicon glyphicon-plus"></span>
  Cadastrar
</a>

<br/><br/>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Sigla</th>
      <th>Descrição</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @specific_practices.each do |specific_practice| %>
      <tr>
        <td><%= specific_practice.name %></td>
        <td><%= specific_practice.abbrev %></td>
        <td><%= specific_practice.description %></td>
        <td><%= link_to 'Visualizar', specific_practice %></td>
        <td><%= link_to 'Editar', edit_specific_practice_path(specific_practice) %></td>
        <td><%= link_to 'Destroy', specific_practice, method: :delete, data: { confirm: 'Voce tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/specific_practices/new.html.erb
<h1>Nova Prática Específica</h1>

<%= render 'form', specific_practice: @specific_practice %>

<%= link_to 'Voltar', specific_practices_path %>

app/views/specific_practices/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @specific_practice.name %>
</p>

<p>
  <strong>Sigla:</strong>
  <%= @specific_practice.abbrev %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @specific_practice.description %>
</p>

<%= link_to 'Editar', edit_specific_practice_path(@specific_practice) %> |
<%= link_to 'Voltar', specific_practices_path %>