config/routes.rb
Rails.application.routes.draw do
  resources :work_products
  resources :categories
  resources :reference_models
  resources :process_areas
  get 'static_pages/home'

  resources :capacity_levels
  resources :maturity_levels
  resources :specific_goals
  resources :specific_practices
  resources :generic_goals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/capacity_level.rb
class CapacityLevel < ApplicationRecord
  has_many :generic_goals
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :process_areas
end

app/models/generic_goal.rb
class GenericGoal < ApplicationRecord
  has_many :capacity_levels
end

app/models/maturity_level.rb
class MaturityLevel < ApplicationRecord
  has_many :process_areas
end

app/models/process_area.rb
class ProcessArea < ApplicationRecord
  belongs_to :reference_model
  belongs_to :category
  belongs_to :maturity_level
end

app/models/reference_model.rb
class ReferenceModel < ApplicationRecord
  belongs_to :area_process
  belongs_to :generic_goal
end

app/models/specific_goal.rb
class SpecificGoal < ApplicationRecord
  belongs_to :specific_practice

  has_many :process_areas
end

app/models/specific_practice.rb
class SpecificPractice < ApplicationRecord
  has_many :specific_goals
end

app/models/work_product.rb
class WorkProduct < ApplicationRecord
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/capacity_levels_helper.rb
module CapacityLevelsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/generic_goals_helper.rb
module GenericGoalsHelper
end

app/helpers/maturity_levels_helper.rb
module MaturityLevelsHelper
end

app/helpers/process_areas_helper.rb
module ProcessAreasHelper
end

app/helpers/reference_models_helper.rb
module ReferenceModelsHelper
end

app/helpers/specific_goals_helper.rb
module SpecificGoalsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/work_products_helper.rb
module WorkProductsHelper
end

app/views/layouts/_footer.html.erb
<footer>
    &copy;2016 - <%= Date.today.year %> CMMI GUIDE. All Rights Reserved.
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-dark bg-inverse">
	<a class="navbar-brand" href="<%= root_path %>">CMMI GUIDE</a>
	<nav>
	  <ul class="nav navbar-nav">
      <li class="dropdown">
        <span>Cadastros</span>
        <ul class="dropdown-content">
          <li><a href="<%= reference_models_path %>">Modelos</a></li>
          <li><a href="<%= categories_path %>">Categorias</a></li>
          <li><a href="<%= process_areas_path %>">Áreas de Processos</a></li>
          <li><a href="<%= generic_goals_path %>">Metas Genéricas</a></li>
          <li><a href="<%= specific_goals_path %>">Metas Específicas</a></li>
          <li><a href="<%= specific_practices_path %>">Práticas Específicas</a></li>
          <li><a href="<%= capacity_levels_path %>">Níveis de Capacidade</a></li>
          <li><a href="<%= maturity_levels_path %>">Níveis de Maturidade</a></li>
        </ul>
      </li>
      <li><a href="<%= work_products_path %>">Produtos de trabalho</a></li>
    </ul>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CmmiGuide</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render('layouts/header') %>

    <br/>

    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>

      <%= yield %>
    </div>
    <%= render('layouts/footer') %>
  </body>
</html>